database:
  mysql-host: '192.168.1.24'
  mysql-user: 'collectivebot'
  mysql-pass: 'password'
  mysql-db: 'Nestdb'
  mysql-tbl: 'first'
parks: ['Freedom','Sandymount']
discord-token: 'NDgyMjE3NzY2OTAwODU4ODkw.DmBr6Q.VnkRdOfBv-zHayGiU14Xn7yZUmU'
admin: [283397773527613441]

